version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: healthcare-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/healthcare
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: healthcare-backend
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/healthcare  # استخدم اسم خدمة MongoDB هنا
      - PORT=3001
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: healthcare-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api 
    restart: unless-stopped

volumes:
  mongodb_data:
