version: '3.8'

services:
  # MongoDB Service (موجود بالفعل)
  mongodb:
    image: mongo:latest
    container_name: healthcare-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=healthcare
    volumes:
      - mongodb_data:/data/db
    networks:
      - healthcare-network

  # Backend Service (ضف هذا)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: healthcare-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/healthcare
      - JWT_SECRET=healthcare-secret-key-2024
    volumes:
      - ./backend/src:/app/src
    networks:
      - healthcare-network
    depends_on:
      - mongodb
    restart: unless-stopped

  # Frontend Service (ضف هذا)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: healthcare-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - healthcare-network
    depends_on:
      - backend

volumes:
  mongodb_data:

networks:
  healthcare-network:
    driver: bridge