services:
  - type: web
    name: healthcare-backend
    env: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        fromDatabase:
          name: healthcare-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: healthcare-mongodb
    plan: free
    databaseName: healthcare
    region: ohio